name: seisk
channels:
- conda-forge
- defaults
dependencies:
- ipython
- basemap
- matplotlib
- numpy
- obspy=1.1.1
- pandas
- pytables
- pytest
- pytest-cov
- pytest-mpl
- python
- scipy
- scikit-learn
- scikit-image
- nitime
- moviepy
- jupyter
- pyqt
- mtspec
- statsmodels
- spyder
- xlrd