name: seisk
channels:
- conda-forge
- defaults
dependencies:
- ipython=4.2.1
- basemap
- matplotlib
- numpy
- obspy
- pandas
- pytables
- pytest
- pytest-cov
- pytest-mpl
- python=3.5
- scipy
- scikit-learn
- scikit-image
- nitime
- moviepy
- jupyter
- pyqt
- mtspec
- statsmodels
- spyder
- xlrd